### ISSUE TITLE
示例错误：请更换为base的示例

### ISSUE THREAD

**Issue by zaixia** [doc-ark-online/api-docs#254]
### 所属页面地址

https://api-docs.ark.online/classes/mw.CharacterDescription.html#base

### 选中内容

CharacterStyleExample 

### 请选择反馈的问题类型

不准确 - 接口调不通/接口参数错误/接口返回和文档不一致

### 补充说明

当前示例是advance的

**Comment by mwking12** [comment]
好哩！

**Comment by zaixia** [comment]
刚注意到，5月份已经提了同样的问题，请尽快修复的。

**Comment by jiahuipeng** [comment]
https://github.com/doc-ark-online/api-docs/pull/268 修复。
