### ISSUE TITLE
缺少默认值说明

### ISSUE THREAD

**Issue by honsrx** [doc-ark-online/api-docs#259]
### 所属页面地址

https://api-docs.ark.online/classes/mw.AvatarSettings.html#accessors

### 选中内容

获取角色优化(角色裁剪、动画更新率降低等)

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

缺少默认值说明

**Comment by jiahuipeng** [comment]
https://github.com/doc-ark-online/api-docs/pull/264
