### ISSUE TITLE
enble是动词，isEnable是错的用法，这里做变量名要用isEnabled

### ISSUE THREAD

**Issue by honsrx** [doc-ark-online/api-docs#260]
### 所属页面地址

https://api-docs.ark.online/classes/mw.AvatarSettings.html#accessors-1

### 选中内容

isEnable

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

### 补充说明

enble是动词，isEnable是错的用法，这里做变量名要用isEnabled

**Comment by jiahuipeng** [comment]
https://github.com/doc-ark-online/api-docs/pull/264
