### ISSUE TITLE
形参大写开头，不符合命名规则 似应改为isEnabled

### ISSUE THREAD

**Issue by honsrx** [doc-ark-online/api-docs#261]
### 所属页面地址

https://api-docs.ark.online/classes/mw.GraphicsSettings.html#methods

### 选中内容

Enabled boolean

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

### 补充说明

形参大写开头，不符合命名规则 似应改为isEnabled

**Comment by jiahuipeng** [comment]
https://github.com/doc-ark-online/api-docs/pull/264
