### ISSUE TITLE
命名方式不统一 bEnable这种方式在其他形参里没见过，似应统一为isEnabled

### ISSUE THREAD

**Issue by honsrx** [doc-ark-online/api-docs#262]
### 所属页面地址

https://api-docs.ark.online/classes/mw.GraphicsSettings.html#getfsrlevel

### 选中内容

bEnable boolean

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

### 补充说明

命名方式不统一 bEnable这种方式在其他形参里没见过，似应统一为isEnabled

**Comment by jiahuipeng** [comment]
https://github.com/doc-ark-online/api-docs/pull/264
