### ISSUE TITLE
非缩写词形参不应以大写字母开头

### ISSUE THREAD

**Issue by honsrx** [doc-ark-online/api-docs#263]
### 所属页面地址

https://api-docs.ark.online/classes/mw.GraphicsSettings.html#getsharpness

### 选中内容

Sharpness number

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

### 补充说明

非缩写词形参不应以大写字母开头

**Comment by jiahuipeng** [comment]
https://github.com/doc-ark-online/api-docs/pull/264
