### ISSUE TITLE
示例错误

### ISSUE THREAD

**Issue by zaixia** [doc-ark-online/api-docs#266]
### 所属页面地址

https://api-docs.ark.online/classes/mw.CharacterDescription.html#base

### 选中内容

myCharacter.description.advance.headFeatures

### 请选择反馈的问题类型

不准确 - 接口调不通/接口参数错误/接口返回和文档不一致

### 补充说明

请更换为base的示例

**Comment by jiahuipeng** [comment]
https://github.com/doc-ark-online/api-docs/pull/268 修复。
