### ISSUE TITLE
这接口咋用啊？

### ISSUE THREAD

**Issue by zhanghexie** [doc-ark-online/api-docs#278]
### 所属页面地址

https://api-docs.ark.online/classes/mw.GameObject.html#getchildbyname

### 选中内容

根据路径查找子物体

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by SneakPeak2003** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
